services:
  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
    ports:
      - "8000:8000"     # Public proxy port
      - "8001:8001"     # Admin API
    volumes:
      - ./kong.yml:/kong/kong.yml

  user-api:
    build: ./UserApi/UserApi
    expose:
      - "8080"
    ports:
      - "9000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Database=share_trip;Username=postgres;Password=postgres
      Jwt__PrivateKeyPath: /keys/private.key
      Jwt__PublicKeyPath: /keys/public.key
    volumes:
      - ./keys:/keys:ro
    depends_on:
      - postgres

  trip-api:
    build: ./TripApi/TripApi
    expose:
      - "8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Database=share_trip;Username=postgres;Password=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
    - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: share_trip

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
    - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
